// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace EqToEq
{
    [ENC.IO.Common.HandlingDataGroup]
    public sealed class BitDeviceMap
    {
        public EqToEq.UpperToSelf.Bits UpperToSelf => mUpperToSelf;
        public EqToEq.SelfToUpper.Bits SelfToUpper => mSelfToUpper;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private EqToEq.UpperToSelf.Bits mUpperToSelf;
        private EqToEq.SelfToUpper.Bits mSelfToUpper;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public BitDeviceMap AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(BitDeviceMap));
            mUpperToSelf = new EqToEq.UpperToSelf.Bits().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(UpperToSelf)].ByteIndex);
            mSelfToUpper = new EqToEq.SelfToUpper.Bits().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(SelfToUpper)].ByteIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(BitDeviceMap)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(BitDeviceMap).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public BitDeviceMapSet BatchRead(BitDeviceMapSet readDataSet)
        {
            UpperToSelf.BatchRead(readDataSet.UpperToSelf);
            SelfToUpper.BatchRead(readDataSet.SelfToUpper);
            return readDataSet;
        }

        public bool BatchWrite(BitDeviceMapSet writeDataSet)
        {
            UpperToSelf.BatchWrite(writeDataSet.UpperToSelf);
            SelfToUpper.BatchWrite(writeDataSet.SelfToUpper);
            return true;
        }
    }
}
