// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace EqToEq
{
    [ENC.IO.Common.HandlingDataGroup]
    public sealed class WordDeviceMap
    {
        public EqToEq.UpperToSelf.Words UpperToSelf => mUpperToSelf;
        public EqToEq.SelfToUpper.Words SelfToUpper => mSelfToUpper;
        public EqToEq.SelfToLower.Words SelfToLower => mSelfToLower;
        public EqToEq.LowerToSelf.Words LowerToSelf => mLowerToSelf;
        public MonitorIO.Words SelfToMonitorIO => mSelfToMonitorIO;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private EqToEq.UpperToSelf.Words mUpperToSelf;
        private EqToEq.SelfToUpper.Words mSelfToUpper;
        private EqToEq.SelfToLower.Words mSelfToLower;
        private EqToEq.LowerToSelf.Words mLowerToSelf;
        private MonitorIO.Words mSelfToMonitorIO;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public WordDeviceMap AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(WordDeviceMap));
            mUpperToSelf = new EqToEq.UpperToSelf.Words().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(UpperToSelf)].ByteIndex);
            mSelfToUpper = new EqToEq.SelfToUpper.Words().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(SelfToUpper)].ByteIndex);
            mSelfToLower = new EqToEq.SelfToLower.Words().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(SelfToLower)].ByteIndex);
            mLowerToSelf = new EqToEq.LowerToSelf.Words().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(LowerToSelf)].ByteIndex);
            mSelfToMonitorIO = new MonitorIO.Words().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(SelfToMonitorIO)].ByteIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(WordDeviceMap)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(WordDeviceMap).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public WordDeviceMapSet BatchRead(WordDeviceMapSet readDataSet)
        {
            UpperToSelf.BatchRead(readDataSet.UpperToSelf);
            SelfToUpper.BatchRead(readDataSet.SelfToUpper);
            SelfToLower.BatchRead(readDataSet.SelfToLower);
            LowerToSelf.BatchRead(readDataSet.LowerToSelf);
            SelfToMonitorIO.BatchRead(readDataSet.SelfToMonitorIO);
            return readDataSet;
        }

        public bool BatchWrite(WordDeviceMapSet writeDataSet)
        {
            UpperToSelf.BatchWrite(writeDataSet.UpperToSelf);
            SelfToUpper.BatchWrite(writeDataSet.SelfToUpper);
            SelfToLower.BatchWrite(writeDataSet.SelfToLower);
            LowerToSelf.BatchWrite(writeDataSet.LowerToSelf);
            SelfToMonitorIO.BatchWrite(writeDataSet.SelfToMonitorIO);
            return true;
        }
    }
}
