// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace EqToEq.SelfToLower
{
    [System.Serializable]
    public sealed class BitsSet
    {
        public bool Heartbeat { get; set; }
        public bool SendAble { get; set; }
        public bool SendStart { get; set; }
        public bool SendComplete { get; set; }
        public bool SendVacuumOffP1 { get; set; }
        public bool SendVacuumOffP2 { get; set; }
        public bool SendCellP1 { get; set; }
        public bool SendCellP2 { get; set; }
        public bool EmsSafe { get; set; }
        public bool InterlockDoorClosed { get; set; }
        public bool InterlockSafe { get; set; }
        public bool Reserved { get; set; }

        public BitsSet()
        {
            var handlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Bits));
        }
    }
}
