// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace EqToEq.SelfToUpper
{
    [System.Serializable]
    public sealed class WordsSet
    {
        public short DUMMY { get; set; }
        public short Reserved { get; set; }

        public WordsSet()
        {
            var handlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Words));
        }
    }
}
