// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace EqToEq.LowerToSelf
{
    [ENC.IO.Common.HandlingDataBlock]
    public sealed class Bits
    {
        public ENC.IO.Common.IHandlingData<bool> Heartbeat => mHeartbeat;
        public ENC.IO.Common.IHandlingData<bool> ReceiveAble => mReceiveAble;
        public ENC.IO.Common.IHandlingData<bool> ReceiveStart => mReceiveStart;
        public ENC.IO.Common.IHandlingData<bool> ReceiveComplete => mReceiveComplete;
        public ENC.IO.Common.IHandlingData<bool> ReceiveVacuumOnP1 => mReceiveVacuumOnP1;
        public ENC.IO.Common.IHandlingData<bool> ReceiveVacuumOnP2 => mReceiveVacuumOnP2;
        public ENC.IO.Common.IHandlingData<bool> ReceiveCellP1 => mReceiveCellP1;
        public ENC.IO.Common.IHandlingData<bool> ReceiveCellP2 => mReceiveCellP2;
        public ENC.IO.Common.IHandlingData<bool> EmsSafe => mEmsSafe;
        public ENC.IO.Common.IHandlingData<bool> InterlockDoorClosed => mInterlockDoorClosed;
        public ENC.IO.Common.IHandlingData<bool> InterlockSafe => mInterlockSafe;
        public ENC.IO.Common.IHandlingData<bool> Reserved => mReserved;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private ENC.IO.Common.IHandlingData<bool> mHeartbeat;
        private ENC.IO.Common.IHandlingData<bool> mReceiveAble;
        private ENC.IO.Common.IHandlingData<bool> mReceiveStart;
        private ENC.IO.Common.IHandlingData<bool> mReceiveComplete;
        private ENC.IO.Common.IHandlingData<bool> mReceiveVacuumOnP1;
        private ENC.IO.Common.IHandlingData<bool> mReceiveVacuumOnP2;
        private ENC.IO.Common.IHandlingData<bool> mReceiveCellP1;
        private ENC.IO.Common.IHandlingData<bool> mReceiveCellP2;
        private ENC.IO.Common.IHandlingData<bool> mEmsSafe;
        private ENC.IO.Common.IHandlingData<bool> mInterlockDoorClosed;
        private ENC.IO.Common.IHandlingData<bool> mInterlockSafe;
        private ENC.IO.Common.IHandlingData<bool> mReserved;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public Bits AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Bits));
            mHeartbeat = ctor.CreateData<bool>(mHandlingData[nameof(Heartbeat)], startIndex);
            mReceiveAble = ctor.CreateData<bool>(mHandlingData[nameof(ReceiveAble)], startIndex);
            mReceiveStart = ctor.CreateData<bool>(mHandlingData[nameof(ReceiveStart)], startIndex);
            mReceiveComplete = ctor.CreateData<bool>(mHandlingData[nameof(ReceiveComplete)], startIndex);
            mReceiveVacuumOnP1 = ctor.CreateData<bool>(mHandlingData[nameof(ReceiveVacuumOnP1)], startIndex);
            mReceiveVacuumOnP2 = ctor.CreateData<bool>(mHandlingData[nameof(ReceiveVacuumOnP2)], startIndex);
            mReceiveCellP1 = ctor.CreateData<bool>(mHandlingData[nameof(ReceiveCellP1)], startIndex);
            mReceiveCellP2 = ctor.CreateData<bool>(mHandlingData[nameof(ReceiveCellP2)], startIndex);
            mEmsSafe = ctor.CreateData<bool>(mHandlingData[nameof(EmsSafe)], startIndex);
            mInterlockDoorClosed = ctor.CreateData<bool>(mHandlingData[nameof(InterlockDoorClosed)], startIndex);
            mInterlockSafe = ctor.CreateData<bool>(mHandlingData[nameof(InterlockSafe)], startIndex);
            mReserved = ctor.CreateData<bool>(mHandlingData[nameof(Reserved)], startIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(Bits)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(Bits).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public BitsSet BatchRead(BitsSet readDataSet)
        {
            readDataSet.Heartbeat = Heartbeat.Value;
            readDataSet.ReceiveAble = ReceiveAble.Value;
            readDataSet.ReceiveStart = ReceiveStart.Value;
            readDataSet.ReceiveComplete = ReceiveComplete.Value;
            readDataSet.ReceiveVacuumOnP1 = ReceiveVacuumOnP1.Value;
            readDataSet.ReceiveVacuumOnP2 = ReceiveVacuumOnP2.Value;
            readDataSet.ReceiveCellP1 = ReceiveCellP1.Value;
            readDataSet.ReceiveCellP2 = ReceiveCellP2.Value;
            readDataSet.EmsSafe = EmsSafe.Value;
            readDataSet.InterlockDoorClosed = InterlockDoorClosed.Value;
            readDataSet.InterlockSafe = InterlockSafe.Value;
            readDataSet.Reserved = Reserved.Value;
            return readDataSet;
        }

        public bool BatchWrite(BitsSet writeDataSet)
        {
            Heartbeat.Value = writeDataSet.Heartbeat;
            ReceiveAble.Value = writeDataSet.ReceiveAble;
            ReceiveStart.Value = writeDataSet.ReceiveStart;
            ReceiveComplete.Value = writeDataSet.ReceiveComplete;
            ReceiveVacuumOnP1.Value = writeDataSet.ReceiveVacuumOnP1;
            ReceiveVacuumOnP2.Value = writeDataSet.ReceiveVacuumOnP2;
            ReceiveCellP1.Value = writeDataSet.ReceiveCellP1;
            ReceiveCellP2.Value = writeDataSet.ReceiveCellP2;
            EmsSafe.Value = writeDataSet.EmsSafe;
            InterlockDoorClosed.Value = writeDataSet.InterlockDoorClosed;
            InterlockSafe.Value = writeDataSet.InterlockSafe;
            Reserved.Value = writeDataSet.Reserved;
            return true;
        }
    }
}
