// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace EqToEq.SelfToLower
{
    [ENC.IO.Common.HandlingDataBlock]
    public sealed class Bits
    {
        public ENC.IO.Common.IHandlingData<bool> Heartbeat => mHeartbeat;
        public ENC.IO.Common.IHandlingData<bool> SendAble => mSendAble;
        public ENC.IO.Common.IHandlingData<bool> SendStart => mSendStart;
        public ENC.IO.Common.IHandlingData<bool> SendComplete => mSendComplete;
        public ENC.IO.Common.IHandlingData<bool> SendVacuumOnP1 => mSendVacuumOnP1;
        public ENC.IO.Common.IHandlingData<bool> SendVacuumOnP2 => mSendVacuumOnP2;
        public ENC.IO.Common.IHandlingData<bool> SendCellP1 => mSendCellP1;
        public ENC.IO.Common.IHandlingData<bool> SendCellP2 => mSendCellP2;
        public ENC.IO.Common.IHandlingData<bool> EmsSafe => mEmsSafe;
        public ENC.IO.Common.IHandlingData<bool> InterlockDoorClosed => mInterlockDoorClosed;
        public ENC.IO.Common.IHandlingData<bool> InterlockSafe => mInterlockSafe;
        public ENC.IO.Common.IHandlingData<bool> Reserved => mReserved;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private ENC.IO.Common.IHandlingData<bool> mHeartbeat;
        private ENC.IO.Common.IHandlingData<bool> mSendAble;
        private ENC.IO.Common.IHandlingData<bool> mSendStart;
        private ENC.IO.Common.IHandlingData<bool> mSendComplete;
        private ENC.IO.Common.IHandlingData<bool> mSendVacuumOnP1;
        private ENC.IO.Common.IHandlingData<bool> mSendVacuumOnP2;
        private ENC.IO.Common.IHandlingData<bool> mSendCellP1;
        private ENC.IO.Common.IHandlingData<bool> mSendCellP2;
        private ENC.IO.Common.IHandlingData<bool> mEmsSafe;
        private ENC.IO.Common.IHandlingData<bool> mInterlockDoorClosed;
        private ENC.IO.Common.IHandlingData<bool> mInterlockSafe;
        private ENC.IO.Common.IHandlingData<bool> mReserved;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public Bits AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Bits));
            mHeartbeat = ctor.CreateData<bool>(mHandlingData[nameof(Heartbeat)], startIndex);
            mSendAble = ctor.CreateData<bool>(mHandlingData[nameof(SendAble)], startIndex);
            mSendStart = ctor.CreateData<bool>(mHandlingData[nameof(SendStart)], startIndex);
            mSendComplete = ctor.CreateData<bool>(mHandlingData[nameof(SendComplete)], startIndex);
            mSendVacuumOnP1 = ctor.CreateData<bool>(mHandlingData[nameof(SendVacuumOnP1)], startIndex);
            mSendVacuumOnP2 = ctor.CreateData<bool>(mHandlingData[nameof(SendVacuumOnP2)], startIndex);
            mSendCellP1 = ctor.CreateData<bool>(mHandlingData[nameof(SendCellP1)], startIndex);
            mSendCellP2 = ctor.CreateData<bool>(mHandlingData[nameof(SendCellP2)], startIndex);
            mEmsSafe = ctor.CreateData<bool>(mHandlingData[nameof(EmsSafe)], startIndex);
            mInterlockDoorClosed = ctor.CreateData<bool>(mHandlingData[nameof(InterlockDoorClosed)], startIndex);
            mInterlockSafe = ctor.CreateData<bool>(mHandlingData[nameof(InterlockSafe)], startIndex);
            mReserved = ctor.CreateData<bool>(mHandlingData[nameof(Reserved)], startIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(Bits)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(Bits).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public BitsSet BatchRead(BitsSet readDataSet)
        {
            readDataSet.Heartbeat = Heartbeat.Value;
            readDataSet.SendAble = SendAble.Value;
            readDataSet.SendStart = SendStart.Value;
            readDataSet.SendComplete = SendComplete.Value;
            readDataSet.SendVacuumOnP1 = SendVacuumOnP1.Value;
            readDataSet.SendVacuumOnP2 = SendVacuumOnP2.Value;
            readDataSet.SendCellP1 = SendCellP1.Value;
            readDataSet.SendCellP2 = SendCellP2.Value;
            readDataSet.EmsSafe = EmsSafe.Value;
            readDataSet.InterlockDoorClosed = InterlockDoorClosed.Value;
            readDataSet.InterlockSafe = InterlockSafe.Value;
            readDataSet.Reserved = Reserved.Value;
            return readDataSet;
        }

        public bool BatchWrite(BitsSet writeDataSet)
        {
            Heartbeat.Value = writeDataSet.Heartbeat;
            SendAble.Value = writeDataSet.SendAble;
            SendStart.Value = writeDataSet.SendStart;
            SendComplete.Value = writeDataSet.SendComplete;
            SendVacuumOnP1.Value = writeDataSet.SendVacuumOnP1;
            SendVacuumOnP2.Value = writeDataSet.SendVacuumOnP2;
            SendCellP1.Value = writeDataSet.SendCellP1;
            SendCellP2.Value = writeDataSet.SendCellP2;
            EmsSafe.Value = writeDataSet.EmsSafe;
            InterlockDoorClosed.Value = writeDataSet.InterlockDoorClosed;
            InterlockSafe.Value = writeDataSet.InterlockSafe;
            Reserved.Value = writeDataSet.Reserved;
            return true;
        }
    }
}
