// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace EqToEq.SelfToLower
{
    [ENC.IO.Common.HandlingDataBlock]
    public sealed class Words
    {
        public ENC.IO.Common.IHandlingData<short> DUMMY => mDUMMY;
        public ENC.IO.Common.IHandlingData<short> Reserved => mReserved;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private ENC.IO.Common.IHandlingData<short> mDUMMY;
        private ENC.IO.Common.IHandlingData<short> mReserved;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public Words AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Words));
            mDUMMY = ctor.CreateData<short>(mHandlingData[nameof(DUMMY)], startIndex);
            mReserved = ctor.CreateData<short>(mHandlingData[nameof(Reserved)], startIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(Words)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(Words).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public WordsSet BatchRead(WordsSet readDataSet)
        {
            readDataSet.DUMMY = DUMMY.Value;
            readDataSet.Reserved = Reserved.Value;
            return readDataSet;
        }

        public bool BatchWrite(WordsSet writeDataSet)
        {
            DUMMY.Value = writeDataSet.DUMMY;
            Reserved.Value = writeDataSet.Reserved;
            return true;
        }
    }
}
