// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace MonitorIO
{
    [ENC.IO.Common.HandlingDataBlock]
    public sealed class Position
    {
        public ENC.IO.Common.IHandlingArrayData<bool> PositionBits => mPositionBits;
        public ENC.IO.Common.IHandlingData<short> CellCount => mCellCount;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private ENC.IO.Common.IHandlingArrayData<bool> mPositionBits;
        private ENC.IO.Common.IHandlingData<short> mCellCount;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public Position AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Position));
            mPositionBits = ctor.CreateArrayData<bool>(mHandlingData[nameof(PositionBits)], startIndex);
            mCellCount = ctor.CreateData<short>(mHandlingData[nameof(CellCount)], startIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(Position)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(Position).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public PositionSet BatchRead(PositionSet readDataSet)
        {
            PositionBits.GetSpanValues(0, readDataSet.PositionBits.AsSpan());
            readDataSet.CellCount = CellCount.Value;
            return readDataSet;
        }

        public bool BatchWrite(PositionSet writeDataSet)
        {
            PositionBits.SetSpanValues(0, writeDataSet.PositionBits.AsSpan());
            CellCount.Value = writeDataSet.CellCount;
            return true;
        }
    }
}
