// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace MonitorIO
{
    [ENC.IO.Common.HandlingDataBlock]
    public sealed class Words
    {
        public MonitorIO.Conveyor EquipmentStatus => mEquipmentStatus;
        public System.Collections.Generic.IReadOnlyList<MonitorIO.Position> ReservedCellPositions => mReservedCellPositions;
        public MonitorIO.Position CellPosition => mCellPosition;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private MonitorIO.Conveyor mEquipmentStatus;
        private System.Collections.Generic.IReadOnlyList<MonitorIO.Position> mReservedCellPositions;
        private MonitorIO.Position mCellPosition;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public Words AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Words));
            mEquipmentStatus = new MonitorIO.Conveyor().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(EquipmentStatus)].ByteIndex);
            mReservedCellPositions = Enumerable.Range(0, mHandlingData[nameof(ReservedCellPositions)].ArrayLength).Select(i => new MonitorIO.Position().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(ReservedCellPositions)].ByteIndex + mHandlingData[nameof(ReservedCellPositions)].HandlingDataSize * i)).ToArray();
            mCellPosition = new MonitorIO.Position().AssignMap(ctor, errorsAndWarnings, startIndex + mHandlingData[nameof(CellPosition)].ByteIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(Words)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(Words).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public WordsSet BatchRead(WordsSet readDataSet)
        {
            EquipmentStatus.BatchRead(readDataSet.EquipmentStatus);
            readDataSet.ReservedCellPositions = ReservedCellPositions.Select(i => i.BatchRead(new MonitorIO.PositionSet())).ToArray();
            CellPosition.BatchRead(readDataSet.CellPosition);
            return readDataSet;
        }

        public bool BatchWrite(WordsSet writeDataSet)
        {
            EquipmentStatus.BatchWrite(writeDataSet.EquipmentStatus);
            Enumerable.Range(0, writeDataSet.ReservedCellPositions.Length).All(i => ReservedCellPositions[i].BatchWrite(writeDataSet.ReservedCellPositions[i]));
            CellPosition.BatchWrite(writeDataSet.CellPosition);
            return true;
        }
    }
}
