// Created by ENC Technology ENC.IO.SoGen
// -----------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구(ENC.IO.SoGen)를 사용하여 생성되었습니다.
// 
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     변경 내용이 손실됩니다.
// </auto-generated>
// -----------------------------------------------------------------------------
using System;
using System.Linq;
using ENC.IO;

namespace MonitorIO
{
    [ENC.IO.Common.HandlingDataBlock]
    public sealed class Conveyor
    {
        public ENC.IO.Common.IHandlingData<bool> Availability => mAvailability;
        public ENC.IO.Common.IHandlingData<bool> Interlock => mInterlock;
        public ENC.IO.Common.IHandlingData<bool> Move => mMove;
        public ENC.IO.Common.IHandlingData<bool> Run => mRun;
        public ENC.IO.Common.IHandlingData<bool> InDelay1 => mInDelay1;
        public ENC.IO.Common.IHandlingData<bool> InDelay2 => mInDelay2;
        public ENC.IO.Common.IHandlingData<bool> WorkDelay1 => mWorkDelay1;
        public ENC.IO.Common.IHandlingData<bool> WorkDelay2 => mWorkDelay2;
        public ENC.IO.Common.IHandlingData<bool> OutDelay1 => mOutDelay1;
        public ENC.IO.Common.IHandlingData<bool> OutDelay2 => mOutDelay2;
        public ENC.IO.Common.IHandlingData<short> CellCount => mCellCount;
        public System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> Informations => mHandlingData;
        private ENC.IO.Common.IHandlingData<bool> mAvailability;
        private ENC.IO.Common.IHandlingData<bool> mInterlock;
        private ENC.IO.Common.IHandlingData<bool> mMove;
        private ENC.IO.Common.IHandlingData<bool> mRun;
        private ENC.IO.Common.IHandlingData<bool> mInDelay1;
        private ENC.IO.Common.IHandlingData<bool> mInDelay2;
        private ENC.IO.Common.IHandlingData<bool> mWorkDelay1;
        private ENC.IO.Common.IHandlingData<bool> mWorkDelay2;
        private ENC.IO.Common.IHandlingData<bool> mOutDelay1;
        private ENC.IO.Common.IHandlingData<bool> mOutDelay2;
        private ENC.IO.Common.IHandlingData<short> mCellCount;
        private System.Collections.Generic.IReadOnlyDictionary<string, ENC.IO.Common.IReadOnlyHandlingDataSet> mHandlingData;

        public Conveyor AssignMap(ENC.IO.Common.IHandlingDataCreator ctor, System.Collections.Generic.List<ENC.IO.Common.ErrorSet> errorsAndWarnings, int startIndex = 0)
        {
            mHandlingData = DataMappingAssignManager.GetDataOrNullFromType(typeof(Conveyor));
            mAvailability = ctor.CreateData<bool>(mHandlingData[nameof(Availability)], startIndex);
            mInterlock = ctor.CreateData<bool>(mHandlingData[nameof(Interlock)], startIndex);
            mMove = ctor.CreateData<bool>(mHandlingData[nameof(Move)], startIndex);
            mRun = ctor.CreateData<bool>(mHandlingData[nameof(Run)], startIndex);
            mInDelay1 = ctor.CreateData<bool>(mHandlingData[nameof(InDelay1)], startIndex);
            mInDelay2 = ctor.CreateData<bool>(mHandlingData[nameof(InDelay2)], startIndex);
            mWorkDelay1 = ctor.CreateData<bool>(mHandlingData[nameof(WorkDelay1)], startIndex);
            mWorkDelay2 = ctor.CreateData<bool>(mHandlingData[nameof(WorkDelay2)], startIndex);
            mOutDelay1 = ctor.CreateData<bool>(mHandlingData[nameof(OutDelay1)], startIndex);
            mOutDelay2 = ctor.CreateData<bool>(mHandlingData[nameof(OutDelay2)], startIndex);
            mCellCount = ctor.CreateData<short>(mHandlingData[nameof(CellCount)], startIndex);
            if (DataMappingAssignManager.GetBlockSize(typeof(Conveyor)) > ctor.FirstIndex + startIndex + ctor.Size)
            {
                errorsAndWarnings.Add(ENC.IO.Common.ErrorSet.CreateError($"타입({typeof(Conveyor).FullName})의 크기가 할당하려는 디바이스({ctor.Name})의 범위를 초과했습니다."));
            }
            return this;
        }

        public ConveyorSet BatchRead(ConveyorSet readDataSet)
        {
            readDataSet.Availability = Availability.Value;
            readDataSet.Interlock = Interlock.Value;
            readDataSet.Move = Move.Value;
            readDataSet.Run = Run.Value;
            readDataSet.InDelay1 = InDelay1.Value;
            readDataSet.InDelay2 = InDelay2.Value;
            readDataSet.WorkDelay1 = WorkDelay1.Value;
            readDataSet.WorkDelay2 = WorkDelay2.Value;
            readDataSet.OutDelay1 = OutDelay1.Value;
            readDataSet.OutDelay2 = OutDelay2.Value;
            readDataSet.CellCount = CellCount.Value;
            return readDataSet;
        }

        public bool BatchWrite(ConveyorSet writeDataSet)
        {
            Availability.Value = writeDataSet.Availability;
            Interlock.Value = writeDataSet.Interlock;
            Move.Value = writeDataSet.Move;
            Run.Value = writeDataSet.Run;
            InDelay1.Value = writeDataSet.InDelay1;
            InDelay2.Value = writeDataSet.InDelay2;
            WorkDelay1.Value = writeDataSet.WorkDelay1;
            WorkDelay2.Value = writeDataSet.WorkDelay2;
            OutDelay1.Value = writeDataSet.OutDelay1;
            OutDelay2.Value = writeDataSet.OutDelay2;
            CellCount.Value = writeDataSet.CellCount;
            return true;
        }
    }
}
